### ISSUE TITLE
Voice Echoing on Rejoin

### ISSUE THREAD

**Issue by MrBl4ckSkull** [KawaiiBone/LethalCompanyRemnants#10]
When we host a game, player voices are normal, but if we close the lobby and rejoin it, everyone has an echoing voice which is frustrating. The only fix we found is to completely relaunch the game.

**Comment by KawaiiBone** [comment]
Thank you for reporting the bug.

This bug should normally be fixed next update of this mod.
Do note that the new version there will be some null errors something about Occlude audio.
But that is only during the loading screen while you make/join a lobby, it should not break the game.
The new version should be coming out today.

**Comment by KawaiiBone** [comment]
Does this issue still occur?
If not then I will close this issue soon.
