### ISSUE TITLE
Remnants item don't despawn on reset or party wipe

### ISSUE THREAD

**Issue by ChristofferBrus** [KawaiiBone/LethalCompanyRemnants#11]
As the title says, remnants item doens't despawn and i don't know why. I know it's a compatibility issue with other mods but i don't know which one and why (175 mods). Thats why i can't give you the errormessage cause it doesn't exist.
But i can give you the thunderstore mod manager code!
018e9988-d9d5-7ed4-5390-2144b751c872

Thanks in advance!
Best regards

**Comment by KawaiiBone** [comment]
That is odd indeed, I tried importing the mods via the code but the install fails.
It seems that the mod PizzaTowerEscapeMusic gives an error and wont let me install the mods.
Could you send the code again but without the PizzaTowerEscapeMusic mod?
Then perhaps it can work and I can take a look at the issue. (I tried installing PizzaTowerEscapeMusic 2.3 alone but it also does not want to be downloaded)

Thank you for reporting the issue.

**Comment by ChristofferBrus** [comment]
Here you go! Thank you for the quick respons. Also uninstalled resonance meltdown that was associated with it.
018e99b7-d0bb-58f7-143a-466a3e72e90f
I dunno if this helps but i suspect that it's either LLL, Late upgrades, Lethal things, generallImprovements or one of the fixes/log cleaners that may be doing it.

**Comment by ChristofferBrus** [comment]
Could also be SellYourStuff? But as i said i have no clue and aint a developer either so i got very little knowledge but tons of guesses

**Comment by KawaiiBone** [comment]
Thanks, I just tested it and it seems to be a bug on my end.
I will upload the bug fix for it today.

Thank you for the fast responses and feedback on the issue.

**Comment by ChristofferBrus** [comment]
Thank you!! I have been trying to fix this for two weeks and thought it was my fault.
You are the man!!

**Comment by ChristofferBrus** [comment]
It seems to work now on partywipe! But i'm unsure if it works when quota is not reached and you get fired. It seems that the items are still there, altho i have just tried it with the mod QuickRestart, so could be a compatibility issue with that mod.

**Comment by KawaiiBone** [comment]
It seems that I have overlooked this part when working on despawning the Remnant items. 
So it is an issue on my end.
It should be fixed on the next update of this mod.

Thank you for the bug report.

**Comment by ChristofferBrus** [comment]
Amazing! Thank you. I don't wanna be annoying but i also found out that some remnant items doesn't despawn when they are in the dungeon. For example, when i have picked up remnant items in the dungeon and then drop it for something else at the exit door. When i well die or fly off for the next round, i can still remnants items i dropped at the exit door from the match before.
Think it affects both inside and outside the dungeon.

**Comment by KawaiiBone** [comment]
Believe me you are not annoying at all.
You are giving clear feedback on issues that I did not notice.

Thank you very much for finding the bugs in this mod.
