### ISSUE TITLE
[Bug] Shotgun and other items are still lost on players besides the host.

### ISSUE THREAD

**Issue by Sourceshard** [KawaiiBone/LethalCompanyRemnants#12]
<img width="596" alt="image" src="https://github.com/KawaiiBone/LethalCompanyRemnants/assets/37197624/f86309a0-e48a-4777-a31b-0aaf59ccddfd">

**Comment by KawaiiBone** [comment]
Thank you for the bug report.
Do you mean that the first part is still present with other players besides host or the second part?
Or both?

**Comment by Sourceshard** [comment]
Both

**Comment by Sourceshard** [comment]
The items disappear from their hands, leaving and rejoining the game the items are gone.

**Comment by KawaiiBone** [comment]
Thank you for reporting this issue fast.
The fix for this version should be uploaded around now.
