### ISSUE TITLE
[ Question/Feature Request] Bodies as scrap limit?

### ISSUE THREAD

**Issue by Sourceshard** [KawaiiBone/LethalCompanyRemnants#13]
When the bodies are set as scrap does it count toward the spawned scrap limit? For example, if 10 items can spawn on a map and I set it for a body to always spawn beside a remnant item. Does this take up two of the ten slots?

If so. Can bodies be changed to not count towards the scrap total and just be tied to the spawn of a remnant item?

**Comment by KawaiiBone** [comment]
No need to worry, the bodies do no count as the scrap limit.
They are spawned separately in a different way then the other scrap.
After the scrap is spawned, the mod start spawning the bodies on the Remnant items.
