### ISSUE TITLE
[Feature Request] Despawn items only at game end, and or tell remnant items apart from other scrap.

### ISSUE THREAD

**Issue by Sourceshard** [KawaiiBone/LethalCompanyRemnants#15]
I would love to have a setting in the config that gives the option that remnant items picked up by the player are considered shop items but still retain their scrap value.

This way if a team wipes, the Remnant items will remain on the ship only disappearing when the game ends and they are voided into space.

I would also love a way of knowing what items are remnant items. That way when purchasing items I can account for item loss if remnant items disappear on a wipe.

**Comment by KawaiiBone** [comment]
This feature is already in this mod, you can enable this feature in the config.
It is in the section called _Save/Load_ and the variable you will need to change is called _Despawn remnant items on party wipe_.

For now the only way you can see the difference in remnant items and shop items is that you can scan remnant items and not shop items, plus remnant items has a scrap value.

Normally you cannot buy remnant items, they can only be found on moons.
