### ISSUE TITLE
During the daily takeoff of the spaceship, delete all remnants

### ISSUE THREAD

**Issue by apeng0907** [KawaiiBone/LethalCompanyRemnants#16]
May I ask if it is possible to add such a setting,
whether they are in the player's hands or on board the ship

**Comment by apeng0907** [comment]
There is another issue with V50, when the Save residual items are set to true, the spaceship will get stuck loading seeds after pulling the joystick.

**Comment by KawaiiBone** [comment]
Thank you for the feature request,

Yes, It is possible to add this feature but I don't understand the use of such a feature.
Could you tell me why you want this feature?

**Comment by KawaiiBone** [comment]
> There is another issue with V50, when the Save residual items are set to true, the spaceship will get stuck loading seeds after pulling the joystick.

Could you tell me more about it?
What kind of mods were you using?
Which errors showed up on the console?

Thank you for reporting the issue.

**Comment by apeng0907** [comment]
I work with InfectedCompany to provide everyone with an equal opportunity to pick up shovels within the facility. However, the current settings cannot adjust the number of shovels that need to be refreshed, and often we cannot find or only have one

**Comment by KawaiiBone** [comment]
For now I can add a feature where it despawns remnant items no matter the situation.
This feature will be there on the next update of the mod.
It can be found in the config in section _Save/load_ and the name is _Always despawn remnant items_.

**Comment by KawaiiBone** [comment]
This feature has now been added to the mod, you can access it via the config in section _Save/load_ and its called _Always despawn remnant items_.

**Comment by apeng0907** [comment]
thanks
