### ISSUE TITLE
[Bug] Stretched Textures

### ISSUE THREAD

**Issue by Sourceshard** [KawaiiBone/LethalCompanyRemnants#17]
![image](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/37197624/e3ccd313-75b0-4ef4-a478-63e1de8ddfca)

As you can see the spray can has a stretched texture. i had this happen with the flashlight as well. I believe it is random.

**Comment by KawaiiBone** [comment]
This could be a small visual bug that occurs with compatibility with other mods.
I have not yet seen this visual bug happen yet.
But if it does not break the game or ruin gameplay, then I think its not something to worry about.

Thank you for reporting the bug.
