### ISSUE TITLE
Crash on random seed

### ISSUE THREAD

**Issue by IAmSympathy** [KawaiiBone/LethalCompanyRemnants#19]
Whenever I try to land on a moon, I get stuck on the random seed screen

Here's the log:
[LogOutput.log](https://github.com/KawaiiBone/LethalCompanyRemnants/files/15041895/LogOutput.log)

**Comment by KawaiiBone** [comment]
Thank you for reporting the issue.

This part is probably an issue with compatibility with other mods.
Could you send me the code of the mods you have used?
So I can test it more thorough and maybe find a way to fix the issue.

This problem does not occur with mods that I use to test, so I cannot know what the specific issue is now.
But I can guess either an incompatibility with mods that adds moons or something else.

**Comment by IAmSympathy** [comment]
Sorry for late response, here is my profile code :
018ef7c6-964b-e896-5342-ac4e1bc8d920

Remnant items rarity was set to 100 for testing purposes

**Comment by KawaiiBone** [comment]
That is all fine I will take a look at this later.
If you want a quick fix for this, then you need to disable the body spawning in the config for the Remnant mods.
You can do this by going to the config section _GeneralBody_ and setting _Body spawn rarity_  value to 0.
This bug should be fixed on the next update.

**Comment by KawaiiBone** [comment]
This is bug on my end, I forgot to take in mind that the prop version of the bodies are not compatible with the random suits version yet. So setting it to scrap should fix the issue as well.
This bug should be fixed on the next update.

Thank you for reporting the bug.

**Comment by KawaiiBone** [comment]
The bug should be fixed now, but ill leave this issue open for a week to be sure.
