### ISSUE TITLE
[Bug/Feature Request] Weird body positions and bodies not being ragdolls

### ISSUE THREAD

**Issue by IAmSympathy** [KawaiiBone/LethalCompanyRemnants#22]
Right now bodies are not being ragdoll and can lead to them being in weird poses or not touching the ground

![Lethal_Company_SEGYpIHr1c](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/110695959/95d3aabd-3704-4f14-938e-75abb9b5288e)
![Lethal_Company_eJWud7GRpE](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/110695959/d049c712-29fb-41dc-8fde-d1f8edabe797)
![Lethal_Company_Z9bryPgBQC](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/110695959/7fdf8384-7b32-415f-b2c2-1e54d44186b7)

Also random feature request: I think we should be able to black list some dead causes for the bodies. For example I'd like to disable bodies being in a cocoon.

**Comment by KawaiiBone** [comment]
For now this is a know issue that I cannot fix yet.
It should not break the game but I know it can be annoying to deal with sometimes.

The reasons why you see different bodies is to give a hint of what kind of monsters there will be spawning on that moon.
Unfortunately, I feel a feature like this would clash with the overall design of the mod, and as such, I don't think I can implement the requested feature at this time.

**Comment by IAmSympathy** [comment]
Understandable, may I as well ask if it could be possible to add compatibility with LethalConfig? Right now the mod doesn't show up in it so we can't configure it in-game.

**Comment by KawaiiBone** [comment]
Sure I will take a look, to see If I can make it work.

Thank you for the feature request.

**Comment by KawaiiBone** [comment]
This might be a bit late, but the mod finally works with Lethal Config.
