### ISSUE TITLE
May I ask if it is possible to add a setting to generate n fixed shovels inside the spacecraft

### ISSUE THREAD

**Issue by apeng0907** [KawaiiBone/LethalCompanyRemnants#24]
Thank you very much for adding the configuration of "Always pay rent items". I really need to pick up shovels inside the facility when playing InfectedCompany, but the current configuration has very limited access to shovels within the facility, with only a few. If possible, you can set a maximum and minimum value for spawn shovels within the facility,

**Comment by KawaiiBone** [comment]
That is sadly a feature that might not be aligned to this mod.
It might in the future work on a feature to control the items more, but it will be a big thing to work on and it will take some time.
If you just want shovels in your spacecraft or spawn them whenever.
I can recommend some other mods that can do that.
I have not tested these mods, but their description does say you can spawn items at will and more.
The mods are [GameMaster](https://thunderstore.io/c/lethal-company/p/GameMasterDevs/GameMaster/) and [DanceTools](https://thunderstore.io/c/lethal-company/p/dancemoon/DanceTools/).

There are probably more mods like this, but these are the ones I found.

Thank you for the feature request.

**Comment by KawaiiBone** [comment]
With the new patch (1.3) you can spawn remnant items separate from normal scrap.
You can tweak a lot of the remnant items spawning in the config file.
This should let you be able to always spawn x amount of shovels on moons.
