### ISSUE TITLE
[Feature Request] Rarity % per item

### ISSUE THREAD

**Issue by MathiusXII** [KawaiiBone/LethalCompanyRemnants#25]
It would be nice to have a % per item rather than based solely off of price/value because only flashlights are spawning since they're so cheap compared to other things

**Comment by KawaiiBone** [comment]
This feature request has been asked a lot lately.
I'm going to put it on my to do list for this mod.
For now this is how I envision the new feature to work:
The place where you can change it would be then in the section _Remnants_ and rather then just a boolean (true or false).
It would be an integer that is from -1 to 100, -1 would be the default and using the credit cost of the store item as what is implemented now. The 0 to 100 would be the spawn rarity from that item and it would be in relative of the spawn rarity of that moon.
Example: the spawn rarity is 5% - 25% of set moon, 0 for that item would be not spawning it, 1% would be 5% for that moon, 50% would be 15% for that moon and 100% would be 25% for that moon.
What are your thoughts on the mechanic?

Thank you for the feature request.

**Comment by MathiusXII** [comment]
That sounds perfect, thanks!

**Comment by MathiusXII** [comment]
Is there no option to edit rarities of items in the "Scrap item list to be used as remnant items"?

**Comment by KawaiiBone** [comment]
> Is there no option to edit rarities of items in the "Scrap item list to be used as remnant items"?

Sadly not because those items cannot be changed in rarity because they are not registered by this mod as scrap.
Which means no rarity or scrap value is calculated by this mod for that item.

Normally you can change those modded scrap from their respective mods.
