### ISSUE TITLE
[BUG] Freeze on Seed Generation

### ISSUE THREAD

**Issue by Sourceshard** [KawaiiBone/LethalCompanyRemnants#26]
[06:17:02.1947127] [Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <787acc3c9a4c471ba7d971300105af24>:IL_0009)
Remnants.Behaviours.SpawnBodiesBehaviour.SpawnBodiesOnItems (System.Collections.Generic.List`1[T] itemsObjects) (at <c0934e2a86ce485c917b94593279f488>:IL_01F2)
Remnants.Patches.RemnantItemsPatch.PatchRemnantItems (System.Object[] __args) (at <c0934e2a86ce485c917b94593279f488>:IL_017E)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::waitForScrapToSpawnToSync>(RoundManager,Unity.Netcode.NetworkObjectReference[],int[])
(wrapper dynamic-method) RoundManager.DMD<RoundManager::SpawnScrapInLevel>(RoundManager)
RoundManager.GeneratedFloorPostProcessing () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_0009)
RoundManager+<LoadNewLevelWait>d__118.MoveNext () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_013C)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

[06:17:02.1947127] [Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <787acc3c9a4c471ba7d971300105af24>:IL_0009)
Remnants.Behaviours.SpawnBodiesBehaviour.SpawnBodiesOnItems (System.Collections.Generic.List`1[T] itemsObjects) (at <c0934e2a86ce485c917b94593279f488>:IL_01F2)
Remnants.Patches.RemnantItemsPatch.PatchRemnantItems (System.Object[] __args) (at <c0934e2a86ce485c917b94593279f488>:IL_017E)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::waitForScrapToSpawnToSync>(RoundManager,Unity.Netcode.NetworkObjectReference[],int[])
(wrapper dynamic-method) RoundManager.DMD<RoundManager::SpawnScrapInLevel>(RoundManager)
RoundManager.GeneratedFloorPostProcessing () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_0009)
RoundManager+<LoadNewLevelWait>d__118.MoveNext () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_013C)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

**Comment by KawaiiBone** [comment]
Could you send me the profile code, so I can test it and fix the bug?

Thank you for the bug report.

**Comment by Sourceshard** [comment]
This is the current Test Pack I am using.

018f16d6-4f19-10a9-9697-2e7d27b26996

**Comment by KawaiiBone** [comment]
Could you tell me more about this bug?
I cannot seem to replicate it, i have tested it on a vanilla and modded moons and it did not crash.
What steps did you had to take to produce this bug?

**Comment by Sourceshard** [comment]
I experienced this bug when pulling the lever to land on a moon. This bug does not always appear. However, when it does it stops the level from generating. The seed will stay displayed on the screen and the level will not load. The previously linked error will appear in the logs.

**Comment by KawaiiBone** [comment]
This could be a bug that happened on a specific moon.
Would you know what moon or moons you were attempted to land on when this bug occurs?

**Comment by Sourceshard** [comment]
I am still unable to reproduce this problem. I will be getting a wider test group soon, maybe we can track it down.

**Comment by KawaiiBone** [comment]
I am grateful that you are doing that. 
The new update from today should make the place were the problem occurred more stable.
It could even be that the problem is solved then.

**Comment by KawaiiBone** [comment]
With no issues heard from others about this bug or something alike.
I will deem this issue as closed.
