### ISSUE TITLE
(Feature Request) Min-Max Scrap Value

### ISSUE THREAD

**Issue by TheComicRelief** [KawaiiBone/LethalCompanyRemnants#27]
I know of the item scrap value percentage but it doesn't sit right with me that it isn't varied like all the other scraps.

**Comment by KawaiiBone** [comment]
Did you mean then a feature that has a min and max scrap value percentage?
Rather then the current one.

Thank you for the feedback.

**Comment by KawaiiBone** [comment]
This feature has been added in the last update (version 1.2.16).
