### ISSUE TITLE
Items "disabled" from being able to be purchased in the store from other mods can still be found in moons

### ISSUE THREAD

**Issue by Fl4sHNoX** [KawaiiBone/LethalCompanyRemnants#3]
Just wanted to report that I've stumbled upon various items added by other mods (such as "FlareGunAmmo" & "RocketLauncher" from [LethalThings](https://github.com/EvaisaDev/LethalThings)) that I have specifically disabled in the config file of the mod to be purchased in the store.

For the record of anyone wondering about this, here's LethalThings' mod dev's comment on the issue I just brought up:

<img width="553" alt="image" src="https://github.com/KawaiiBone/LethalCompanyRemnants/assets/3759901/898c4b7d-c481-4baa-a6e6-33dbd88b7fc5">

> From the official "Lethal Things" thread on the "Lethal Company Modding" Discord server https://discord.com/channels/1168655651455639582/1178456016254414878/1212091838358356029

EDIT: I just realized that the issue I'm mentioning is already discussed and turned into a suggestion in the following comment:
https://github.com/KawaiiBone/LethalCompanyRemnants/issues/1#issue-2141976716

**Comment by KawaiiBone** [comment]
That is something troubling indeed, I'm going to first see if I can fix the issue. 
Because I feel bad that my mod is disrupting other mods.
After that I will work fully on the config.
Thank for reporting this bug.

**Comment by Fl4sHNoX** [comment]
No worries! And I don't think your mod is disrupting anything, it's simply having an unexpected behavior with some other mods.

And for the record somebody suggested to use [LethalQuantities](https://github.com/BananaPuncher714/LethalQuantities) to set the "Rarity" of those items to 0 so that they do not spawn. 

<img width="478" alt="image" src="https://github.com/KawaiiBone/LethalCompanyRemnants/assets/3759901/51691ef6-ccf1-4597-b4f8-9432588ef361">

> From the official "Lethal Things" thread on the "Lethal Company Modding" Discord server
> https://discord.com/channels/1168655651455639582/1178456016254414878/1212095781473886208

So far this workaround seems to work although it's obviously not as straightforward as it could be without having to play around with editing spawn-rates through the use of another mod like LQ.

**Comment by KawaiiBone** [comment]
Normally the update now should fix the issue, you can now ban items that got added as scrap via this mod.
![RemnantsListExample](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/159925618/16ec9853-87b1-4b3b-873b-eae9d8cd1a6d)

**Comment by Fl4sHNoX** [comment]
I'm not finding any config file nor "RemnantsSpawnableList.json" after updating, launching the game and a new save.

**Comment by KawaiiBone** [comment]
It is not next to the mod, but rather where the save files are located.
Location: C:\Users\(username)\AppData\LocalLow\ZeekerssRBLX\Lethal Company

![RemnantsPathExample](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/159925618/69a8b56e-801a-4440-a17c-3ec821c13aa6)

**Comment by Fl4sHNoX** [comment]
Wait am I understanding it wrong or is it not going to be shared through r2modman profiles?

**Comment by KawaiiBone** [comment]
I do not know what r2modman profiles are, but ill check it out tomorrow and see if i can make it work.
