### ISSUE TITLE
[Bug] Remnant can't be set to no credits

### ISSUE THREAD

**Issue by JohnMetroid** [KawaiiBone/LethalCompanyRemnants#33]
hey there,

in previous remnant versions, settings min/max to 0 scrap would drop remnants with no credit value.  After the update, the same settings generate remnant items at 1 credit with these settings

![image](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/139426529/85eb3226-9209-4215-9775-f3e3b46ed63c)
![image](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/139426529/5b19f593-f005-4132-8d2f-c536e0189cf9)

**Comment by KawaiiBone** [comment]
It seems that I made a mistake and made the minimum scrap value of remnant items to 1% of its credits value.
This issue will be fixed on the next update of this mod.

Thank you for reporting the bug.

**Comment by JohnMetroid** [comment]
thanks for confirming!

kudos on the update, by the way.  The improvements are great :)

**Comment by KawaiiBone** [comment]
This issue is fixed on the latest update (1.3.2).

If there is still an issue around it, you create a new issue here on GitHub.
