### ISSUE TITLE
Minimum Remnant Items Spawned

### ISSUE THREAD

**Issue by MadKattz** [KawaiiBone/LethalCompanyRemnants#36]
Not sure if this is intentional, but I've been trying to change the spawn rates of items on early moons to be considerably rare, since the danger level of these moons is supposed to be pretty low. However, the config for minimum items spawned on a moon cant be set lower than 1, guaranteeing a dead body to spawn on each level.

**Comment by KawaiiBone** [comment]
To change the spawn rates relatively to the danger of the moons, its best to tweak these two config features:
- _Remnant items spawn modifier_ (Section Spawning): this is a modifier relative to the threat level of the moon, lowering this number decreases the amount of remnant items spawning on moons. The higher the risk level, the more influence the modifier will have.
-  _Body spawn modifier per moon risk level_ (Section GeneralBody): This works the same way but for bodies.

Do know that a moon like Experimentation has a high level of threat and for example Vow has a very low one.
Is this what you meant?

**Comment by MadKattz** [comment]
Basically, im just trying to set this value to 0. I'm not sure if its a limitation in the code but it keeps changing to 1 every time I launch to game and check back.

![Capture](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/73416136/f4507efb-5cf9-438b-8e75-98f89005a3dc)

**Comment by KawaiiBone** [comment]
It is a set limitation that I put in, I basically clamp the number between 1 and 50 to prevent it crashing the game.
I would recommend you reducing the config features that I mention to a number like 0.05 or lower.
This means that there is a chance that no items or bodies will spawn on a level.
