### ISSUE TITLE
Scrap spawns without item value

### ISSUE THREAD

**Issue by Fl4sHNoX** [KawaiiBone/LethalCompanyRemnants#4]
I just found a new bug that I think may be caused by this mod as when I deactivated it the scrap item value seemed to have returned? It will need further testing but so far here's what it looks like:

![20240228182942_1](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/3759901/30a8f3d6-e0e1-45a6-aa60-e733f28d67dd)
![20240228185828_1](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/3759901/7c2f45e2-a690-4169-9d4d-a0f327193769)

**Comment by RosinRush** [comment]
yep ditto

**Comment by KawaiiBone** [comment]
Good news, this issue should be fixed in the next update today.
It was caused by a syncing issue with items and its value, normally it is only a visual bug.

**Comment by Fl4sHNoX** [comment]
Can confirm that so far it seems to be working for most items, although I would like to report that there seems to be some possible "soft-incompatibility" with [LCMod-sellYourStuff](https://github.com/tri-white/LCMod-sellYourStuff) as some items show the selling price like the Pro-Flashlight, but some others like the Shovel don't.

Prior to the update that caused the issue those prices were both showing when scanning.

---

**UPDATE: It seems that I may be mistaken and that it may not be related to LethalCompanyRemnants, needs further testing.**

**Comment by KawaiiBone** [comment]
Does this issue still occur?
If not then I shall close this issue soon.

**Comment by Fl4sHNoX** [comment]
It doesn't seem to occur anymore! Thanks again for your work!
