### ISSUE TITLE
[Bug] I broke remnant spawning (sorry)

### ISSUE THREAD

**Issue by JohnMetroid** [KawaiiBone/LethalCompanyRemnants#40]
Hey there,

I was tweaking some of the spawn settings to test the behavior and see what happened.  I created a config to try to spawn 3 items per body.  Otherwise the config should be nearly identical to the previous one in my last ticket.  When setting spawns-per-remnant to 3, it seems like I broke the remnant spawning system.  The log doesn't list any remnant items like it usually seems to.

```
[01:18:50.1773999] [Info   :KawaiiBone.Remnants] Patching spawn remnant items.
[01:18:50.2204096] [Info   :KawaiiBone.Remnants] Patching end of Spawn Scrap.
```

I dropped a few times, and saw remnants with this config on subsequent drops.  One thing I **did** notice was a remnant corpse that only had 2 drops (despite the config specifying [3,3]).  My naive guess is remnant may stop trying to drop remnants/items after it hits an error trying to drop an item that has hit it's "cap" based on the specified weights?

Config added below.

[Remnants.txt](https://github.com/user-attachments/files/16536426/Remnants.txt)

Also log for 3 drops (first one seemed to have no remnants, 2nd drop observed remnant with only 2 items, 3rd was uneventful)
[LogOutput.log](https://github.com/user-attachments/files/16536456/LogOutput.log)

**Comment by KawaiiBone** [comment]
This seems to be a a bug or compatibility issue with other mods, since I can't replicate it in vanilla.
I see it's a lot of mods that you used which in the end can cause problems.
Could you send me the code for the mods?
So I can test it better myself and maybe find the problem.

There are some fail safes indeed to prevent crashes from this mod, which makes it so that some items or bodies might now spawn.
It also prevents some shop items, moons or suits from being used in this mod. Of course, this does not suppress the mod, but rather prevent the Remnant mod from interacting/using that mod.

Thank you for the bug report and no need to say sorry you are helping a lot.

**Comment by JohnMetroid** [comment]
Of course, here's a mod profile that was in use at the time.  The remnant config has been set back to nominal levels -- you'll want to refer to the one uploaded here as "Remnants.txt" above.  You may be on to something in regards to a mod conflict. I don't think i've ever seen the Axe drop, for instance.  I'm going to try to put a bit more time into that mod pack tonight if I can find some time, and I'll update this if I find anything interesting

Profile code: 019131d8-1cc3-f321-2398-3fbcb5fd5eea

For reference: I dropped on Vow 3x times in the log that was posted.  Drop 1) had no apparent remnant spawns.  2) and 3) had remnant spawns.

**Comment by JohnMetroid** [comment]
No major update, but after forcing the axe to spawn by increasing its weight to 100, I did finally see the axe so I don't think that modded item is the problem

When setting the drops-per-remnant to [3,3] again, I found a body with only 1 drop on my first check.  Perhaps the issue is the drop logic when selecting multiple items for a corpse and running up against some sort of drop constraint (e.g. trying to drop Jetpack after an internal limit has already been hit?).  Or perhaps it just isn't enforcing this setting properly at present (though the vast majority of corpses do indeed have 3 items, so that seems less likely)

![image](https://github.com/user-attachments/assets/87e91be5-2360-4310-8184-ff406068c591)

The 2nd vow check seemed perfectly fine.  On the 3rd vow check, I seem to have broken the remnant spawn system in the same way as before.  I found one corpse with 3 items, and couldn't find anything else in the level.  I might have missed one or two in the pipes, but I don't think there was anything close to remnant cap, and the log seems to confirm that from the battery logging

![image](https://github.com/user-attachments/assets/fdd90c9f-e348-4336-9c73-ea9600777bd3)

Log and config attached:
[Remnants.txt](https://github.com/user-attachments/files/16557013/Remnants.txt)
[LogOutput.log](https://github.com/user-attachments/files/16557016/LogOutput.log)

As a minor note aside from this specific report, I've noticed that when remnants drop multiple items there's no restriction on dropping duplicates of the same item.  It would be great if there was at least an optional config setting to prevent dupes on a single corpse.  Not a deal-breaker for me specifically since I'm ok setting remnants to [1,2] and tolerating infrequent dupes, but thought I'd document it for you

![image](https://github.com/user-attachments/assets/a96fa5a5-eb58-46e9-8537-ce82f8ef0e48)

and as long as I'm documenting minor oddities with spawning behavior, the current spawn system allows corpses and items to spawn right next to a wall.  It isn't game breaking or a major enough issue to consider a bug, but it would be great if drops were required to be some small distance from the wall. I'm not sure if you can even detect a wall when spawning, so I definitely understand if this isn't feasible at present.  Just figured I'd log the behavior here since I see it occasionally

stack of corpse and 3 items right up against the wall:
![image](https://github.com/user-attachments/assets/3ad30509-1d69-47f9-b73d-0759ed40b9ec)

edit: profile code from before should still be fine.  If you'd like me to remove the documentation of the minor spawning stuff and move them to a different ticket, just let me know

**Comment by KawaiiBone** [comment]
I will now take a look at it and see what is going on, the reason why you don't see many items or bodies spawn. Is because it is denied due to something going wrong. Which I still need to figure out, but the quick fix for it if you want to use the Remnants mod is by using the legacy spawning.

Thank you for the detailed bug report.

**Comment by JohnMetroid** [comment]
no worries, the good news is the bug doesn't seem to cause issues anywhere outside of remnant spawns. I can tolerate the occasional day with non-existant remnant spawning for now. :)

if you find that you need anything else, just let me know

**Comment by KawaiiBone** [comment]
So the main issue was that the remnant items sometimes could not find a good place on the ground (navmesh) which caused this bug. This was mainly an issue for modded maps since I did not test these features on it.

Normally, this issue is fixed now with the new update.
Thank you again for helping.

**Comment by JohnMetroid** [comment]
Going to close this out since the bug in OP was fixed, and the suggested stuff was super minor and doesn't warrant keeping the ticket open.

Thanks again
