### ISSUE TITLE
Remnant items cannot be stored inside of Belt Bag because they are considered scrap instead of tools

### ISSUE THREAD

**Issue by thaatds233** [KawaiiBone/LethalCompanyRemnants#42]
The new belt bag added in v64 can't store Remnant items inside of it because they are considered to be scrap instead of tools.

**Comment by MasterSquinch** [comment]
Opened up GitHub to mention this exact issue.

**Comment by thaatds233** [comment]
I don't know if this can be fixed without changing how this whole mod works, because it seems to entirely work by converting the tools into scrap.
You can use the BagConfig mod and manually add all the store items into the allowlist as a workaround to this issue.

Pasting this into the Item Categories line in the config will allow all Remnant items to be stored inside the bag:
`Extension ladder: Tools, Lockpicker: Tools, Pro-flashlight: Tools, Radar-booster: Tools, Spray paint: Tools, Stun grenade: Tools, TZP-Inhalant: Tools, Walkie-talkie: Tools, Zap gun: Tools, Weed killer: Tools, Boombox: Tools, Flashlight: Tools, Jetpack: Tools, Key: Tools, Shovel: Tools, Shells: Tools, Belt bag: Tools
`

**Comment by KawaiiBone** [comment]
> I don't know if this can be fixed without changing how this whole mod works, because it seems to entirely work by converting the tools into scrap. You can use the BagConfig mod and manually add all the store items into the allowlist as a workaround to this issue.
> 
> Pasting this into the Item Categories line in the config will allow all Remnant items to be stored inside the bag: `Extension ladder: Tools, Lockpicker: Tools, Pro-flashlight: Tools, Radar-booster: Tools, Spray paint: Tools, Stun grenade: Tools, TZP-Inhalant: Tools, Walkie-talkie: Tools, Zap gun: Tools, Weed killer: Tools, Boombox: Tools, Flashlight: Tools, Jetpack: Tools, Key: Tools, Shovel: Tools, Shells: Tools, Belt bag: Tools `

This seems to be indeed the best way to fix this issue. Since like you said it would be inconvenient to fix this issue on my end.
If it comes to it and I work on this mod further, I might find an alternate way to fix this issue on my end.

Thank you for the issue report and the way to fix it.

**Comment by MasterSquinch** [comment]
Would it be a good idea to reach out to the author of that mod, and maybe fork this one to integrate the functionality? 

Or even just to fork and try a new method of spawning the items?

**Comment by JohnMetroid** [comment]
Hey there,

I was also going to report this issue.  Appreciate everyone else taking the time to do so.

It might be worth mentioning my specific use case:  I spawn remnant items with no credit value.  In the case when remnant drops are set to 0 credits, would it be possible to detect this and simply drop them as the normal version of the item instead of scrap?

Cheers

**Comment by KawaiiBone** [comment]
I found a good way to make sure that the belt bag item also accepts remnant items.
Along that, there will be a config feature allowing you to disable/enable this feature if it does not suit you or creates problems with mods that also changes the belt bag item.
This feature will be in there on the next update, which will be this week.

**Comment by KawaiiBone** [comment]
The new version has been uploaded.
This means that the feature request is completed.
I will leave this issue open for a couple of weeks, if there are issues with the feature.

**Comment by JohnMetroid** [comment]
I did some very brief testing with the new option, and it seems fine as far as I can tell.

Thanks for the update :)
