### ISSUE TITLE
[Request] Config to randomize body scrap value within min/max range

### ISSUE THREAD

**Issue by tisajokt** [KawaiiBone/LethalCompanyRemnants#43]
In a world where nearly every other piece of scrap has a range of possible values, it's weird for all bodies to have the exact same default value of 5 (though I like the aesthetic of retrieving bodies being rare but valuable to retrieve, so I play with them at 75, which exacerbates the issue since a consistently 75-valued scrap is rather conspicuous)

**Comment by KawaiiBone** [comment]
You are right on that, it would indeed be good if the bodies scrap value would scale in size just like the other scrap. 
Since they are basically the same mechanically as scrap in this mod.
When I have time, I will be sure to add this feature in.

Thank you for the feature request.

**Comment by KawaiiBone** [comment]
The new version has been uploaded.
This means that the feature request is completed.
I will leave this issue open for a couple of weeks, if there are issues with the feature.
