### ISSUE TITLE
Crash on random seed

### ISSUE THREAD

**Issue by TheRealMrKam** [KawaiiBone/LethalCompanyRemnants#5]
Hello, just tried new version and it crashed on stratup (seed)

Seem to be a problem with SpawnBodiesPatch

Config is untouched

[LogOutput.log](https://github.com/KawaiiBone/LethalCompanyRemnants/files/14578984/LogOutput.log)

**Comment by KawaiiBone** [comment]
Thank you for reporting the bug. 
It seems It could not find the asset bundle of remnants and I did not correctly made a check on that.
So when it would go through SpawnBodiesPatch, it would crash.
A fix on this will be uploaded today very soon.

**Comment by KawaiiBone** [comment]
A follow up, are you using the Thunderstore to install this mod?
Because it seems odd, that It could not find the asset bundle remnants.

**Comment by KawaiiBone** [comment]
I just made a new upload for the mod, which should fix your current issue.

**Comment by TheRealMrKam** [comment]
Ok thank you i'll try now !

**Comment by TheRealMrKam** [comment]
> A follow up, are you using the Thunderstore to install this mod? Because it seems odd, that It could not find the asset bundle remnants.

I'm downloading in thunderstore and installing manually ( without mod manager)

**Comment by KawaiiBone** [comment]
> > A follow up, are you using the Thunderstore to install this mod? Because it seems odd, that It could not find the asset bundle remnants.
> 
> I'm downloading in thunderstore and installing manually ( without mod manager)

Alright, well be sure to add the file called remnants in to the plugins folder, it is where you should normally put the remnants.dll file. 
It is the asset bundle so it can load the bodies.
If that was done and you still have a log error that says "Assetbundle remnants not found".
Which can appear after it says "modGUID has started", be sure to tell me.
Unless of course you don't want the bodies to be spawned, then you can just leave it be.

**Comment by TheRealMrKam** [comment]
Ok it doesn't block on seed anymore !

But i wasn't able to find any bodies, nor can i spawn them with mods like dancetools as scrap.

Also some items seem to spawn outside the dungeon :

![image](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/154998012/c6223c47-780f-40a3-a3c9-99fa1450a589)

**Comment by TheRealMrKam** [comment]
> > > A follow up, are you using the Thunderstore to install this mod? Because it seems odd, that It could not find the asset bundle remnants.
> > 
> > 
> > I'm downloading in thunderstore and installing manually ( without mod manager)
> 
> Alright, well be sure to add the file called remnants in to the plugins folder, it is where you should normally put the remnants.dll file. It is the asset bundle so it can load the bodies. If that was done and you still have a log error that says "Assetbundle remnants not found". Which can appear after it says "modGUID has started", be sure to tell me. Unless of course you don't want the bodies to be spawned, then you can just leave it be.

Yes i do have it like this in plugins like other mods with his bundle :
![image](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/154998012/4db9e779-1d26-4062-9974-3e8b5250dfe9)

it does tell me " [Error  :KawaiiBone.Remnants] Assetbundle remnants not found."  in the log

Does it not accept to be inside a folder?

EDIT: Ok they spawn now that i put it on plugin without a folder ! Thank you !
I noticed body aren't grabbable, explains also why i can't spawn them

**Comment by KawaiiBone** [comment]
Yeah it seems to be best to put it outside of the remnants folder file and just in the plugins folder.
Normally then it should spawn bodies. It would say it in the log that it has loaded x asset then.
I will update it later on that it is also compatible in the way you did it.

The spawning outside of the dungeon is not intended, I will see how I can fix this issue.
Thank you for the very clear feedback and reports of issues. :)

**Comment by TheRealMrKam** [comment]
You are welcome ! :) 

Is there any way you can make the bodies as grabbable scrap ?

**Comment by KawaiiBone** [comment]
I've looked into applying just this feature before, but unfortunately I was met with a series of issues that I couldn't solve as of yet. As such, I've had to settle for making the bodies something akin to a prop for the time being. 
The current priority is for me to fix bugs, adding other features and make sure the mod runs smoothly, but once all of that is done, I'd be happy to look into this again!

**Comment by TheRealMrKam** [comment]
I see, someone got it working on this mod, but it adds a lot of other things. If you want to look at the code on how he did it:

https://thunderstore.io/c/lethal-company/p/malco/CleaningCompany/

**Comment by TheRealMrKam** [comment]
Hello ! First of all, thank you for the update with the grabbable bodies, i've been waiting for this for so much time ! :)

Noticed that the ragdoll stops after 2 seconds, it's  possible to make them ragdoll like normal bodies in a future update ? (or maybe optional in config ?)

Also the webbed one doesn't have the web texture, is that normal?

![image](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/154998012/f97556aa-f046-474e-bef9-bebc1045ae7c)

**Comment by KawaiiBone** [comment]
That is nice to hear, i am glad that you are enjoying it. :)

Indeed, for now it is like this on purpose because the ragdoll jitters too much.
I will try to fix this issue later on, I think it is a collision issue because the ragdoll does not have this problem when it is a prop.

You are right it is not normal, I just looked and it seems that I forgot to add the textures to the material.
The fixed version will be uploaded in the next update.
Thank you for reporting the issue.

**Comment by KawaiiBone** [comment]
I have tried a lot to make the body less clunky, but it did not work sadly.
