### ISSUE TITLE
[Massive Bug Report] EVERYTHING Disappears on Team Wipe

### ISSUE THREAD

**Issue by ElvenWitchBirdy** [KawaiiBone/LethalCompanyRemnants#6]
Hi, me again.

The newest updates 1.2.0 and 1.2.1 erases everything in the ship on team wipe and borks compatibility with loot saving mods. Restoring the mod to version 1.1.7 returns everything back to normal. It's not just loot that disappears but all the equipment as well. The only objects that remain is ship furniture.

The loot saving mods installed: SaveOurLoot, LategameUpgrades, and AdvancedCompany (1.1.13).

**Comment by KawaiiBone** [comment]
Thank you for reporting this bug.
Could you elaborate on _all the equipment as well_?
First I will make sure it will only wipe out remnant items and after that give you an option to enable/disable the load and save functions of this mod.
The first part will definitely be upload today.

**Comment by ElvenWitchBirdy** [comment]
I meant absolutely everything. Both the remnant variants and the store variants of all the purchasable equipment get wiped out completely, along with the loot. Wiped clean.

**Comment by KawaiiBone** [comment]
Alright, I just uploaded the new version of the mod.
That should normally fix all the bugs you have mentioned.
About the despawn all items issue, now it only does remnant items, and If you want it to not be despawned.
You can just go in the config in the Save/load section and set "Despawn remnant items on party wipe" to false.

**Comment by KawaiiBone** [comment]
Does this issue still occur?
If not then I shall close this issue soon.
