### ISSUE TITLE
Not sure if it's an issue or just a funny bug

### ISSUE THREAD

**Issue by Fl4sHNoX** [KawaiiBone/LethalCompanyRemnants#7]
I'm not sure if we're supposed to be able to "grab" the body or anything but I wasn't able to, and I assume it spawned in the place where some loot can spawn in these closets:

![20240315050946_1](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/3759901/20967c46-c556-428f-8e37-77be460f8a0e)

**Comment by KawaiiBone** [comment]
The body for now is not supposed to be grabbed and is more like a prop.
So the way the body spawning works, is that it goes through all the remnant items and then spawns on them. 
Of course not on every remnant item, but each remnant item has a chance for a body to be spawned on it.
Which means it can spawn in the closet, which I hope is a funny sight to behold.

But I already heard a suggestion from someone else for also wanting the body to be able to be grabbed.
Is that something you want as well, would it be fun to have in this mod?
With that I will also work on better spawning locations for the body if it is too odd. 

Thank you for reporting the feedback and issue.

**Comment by Fl4sHNoX** [comment]
Ah I see, thanks for the detailed explanation!
It did give me a bit of a chuckle so I personally find it funny, I was just wondering if it was an intended behavior.

I guess it may just seem counter-intuitive to not be able to grab the body since you can do so with the ones from your teammates, and also basically most things you can scan inside the facility.

I'm always interested in options so in case someone prefers to have them as props and not being able to be grabbed, maybe having it as an option in the config could be an idea, although I wouldn't want it to be some annoying extra work if you preferred to just make them only grabbable.

What I'm wondering mainly is if it would count as an actual corpse and could "combo" with the [MaskTheDead](https://github.com/RealPlanet/MaskTheDead) mod, and have the potential to have "corpses of the previous crew that went on the moon be possessed" if they spawn in the vicinity of a mask.

**Comment by KawaiiBone** [comment]
I uploaded a new version of this mod and that should fix the bodies spawning in lockers.

About your suggestion, I have added it on the backlog. 
So I will be working on making a grabbable body soon.

For the compatibility with the MaskTheDead mod, I think It will be difficult because it looks for the component RagdollGrabbableObject. 
Which is a unique GrabbableObject that is linked to a player, this makes it more difficult because the bodies the Remnants mods spawn will probably not be using the RagdollGrabbableObject for its requirements and a need of a link to a player.
But I can always see If I can make it work.

**Comment by Fl4sHNoX** [comment]
Maybe we can ask the author of MaskTheDead to include an optional feature that also search for your bodies?

**Comment by KawaiiBone** [comment]
Yeah, I shall ask when I am working on making the body grabbable.

**Comment by KawaiiBone** [comment]
I have asked about it two weeks ago, but I got no answer sadly yet.
If I hear about it, I will do my attempt to help and make it compatible. 

For now I will close this issue then.
