### ISSUE TITLE
Endless loading with some modded moons

### ISSUE THREAD

**Issue by Jimmerslock** [KawaiiBone/LethalCompanyRemnants#8]
The moded moons of [Anor Londo](https://thunderstore.io/c/lethal-company/p/Dounat12/Anor_Londo/) and [Dust2](https://thunderstore.io/c/lethal-company/p/ake/Dust2/) load endlessly with this mod, it appears they are missing some keyword since it seems that even [LethalLevelLoader](https://thunderstore.io/c/lethal-company/p/IAmBatby/LethalLevelLoader/) is having a problem with it in the config files, I doubt this is an issue on the part of your mod but I thought it was still worth noting.

**Comment by KawaiiBone** [comment]
I just tested it and it seems to be a bug indeed from this mod Remnants.
This issue happens when the Remnants mod attempts to get its prefabs to spawn bodies, but it acquires the wrong one.  
I will work on this issue asap.

Thank you for reporting the bug.

**Comment by Jimmerslock** [comment]
oh huh! Well uh, thank you then!

**Comment by KawaiiBone** [comment]
It was actually something else entirely, just a part of this mod was not well compatible with custom moons.
But I uploaded a new version now that should fix that issue.

**Comment by KawaiiBone** [comment]
Does this issue still occur?
If not then I will close this issue soon.

**Comment by Jimmerslock** [comment]
oh sorry, yeah it doesn't occur anymore. Thanks for the work!
