### ISSUE TITLE
Possible compatibility with SellYourStuff

### ISSUE THREAD

**Issue by Jimmerslock** [KawaiiBone/LethalCompanyRemnants#9]
this is more of a suggestion but I wondered if this mod could be more compatible with [SellYourStuff](https://thunderstore.io/c/lethal-company/p/KawaiiBone/Remnants/), a mod that allows you to sell company equipment back to the company, I think the reason why it doesn't work is because the spawned equipment from Remnants has no assigned store bought value and thus it just sell back for 0. 

Perhaps if you could edit a config and/or items just spawn with their store prices could fix it.

**Comment by KawaiiBone** [comment]
Thank you for the suggestion,
I can definitely see if I can make it work, normally it should be easy and like you said It will be a config value.
The current way on how the spawned equipment/remnant items scrap cost work, I just set the scrap value to zero.
This is just a decision I made for making this mod a bit more balanced.

 If everything goes well, you will see this feature be added in the next update or the one after that.

**Comment by KawaiiBone** [comment]
I uploaded a new version which should fix the compatibility with SellYourStuff.
In the config look in the  "Other" section to edit the percentage scrap value of the remnant item.
100 is to get the full price of the item as scrap value, on default it is on 0.

**Comment by Jimmerslock** [comment]
thanks you!
